apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    # some comments about this source
    path: manifests/gke_dev_europe-west4_gc-dev-kube0/grafana
    repoURL: https://github.com/idsvandermolen/config-management.git
    targetRevision: HEAD
