apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kibana
spec:
  maxReplicas: 12
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kibana
  targetCPUUtilizationPercentage: 80
