apiVersion: apps/v1
kind: Deployment
metdata:
  name: prometheus
  labels:
    name: prometheus
spec:
  selector:
    matchLabels:
      name: prometheus
  template:
    spec:
      metadata:
        labels:
          name: prometheus
      containers:
        - image: prom/prometheus
          name: prometheus
          ports:
            - containerPort: 9090
              name: api
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
