apiVersion: apps/v1
kind: Deployment
metdata:
  name: prometheus
  labels: &Labels
    app.kubernetes.io/name: prometheus
spec:
  selector:
    matchLabels: *Labels
  template:
    spec:
      metadata:
        labels: *Labels
      containers:
        - name: prometheus
          image: prometheus
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
