apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/gke_prd_europe-west4_gc-prd-kube0/grafana
    repoURL: https://github.com/idsvandermolen/config-management.git
    targetRevision: HEAD
