apiVersion: apps/v1
kind: Deployment
metdata:
  labels: &id001
    app.kubernetes.io/name: grafana
  name: grafana
spec:
  selector:
    matchLabels: *id001
  template:
    spec:
      containers:
      - image: grafana
        name: grafana
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: '8'
            memory: 8G
          requests:
            cpu: '8'
            memory: 8G
      metadata:
        labels: *id001
