apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      name: grafana
  template:
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        ports:
        - containerPort: 3000
          name: ui
        resources:
          limits:
            cpu: '8'
            memory: 8G
          requests:
            cpu: '8'
            memory: 8G
      metadata:
        labels:
          name: grafana
