apiVersion: apps/v1
kind: Deployment
metdata:
  labels: &id001
    app.kubernetes.io/name: kibana
  name: kibana
spec:
  selector:
    matchLabels: *id001
  template:
    spec:
      containers:
      - image: kibana
        name: kibana
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: '2'
            memory: 2G
          requests:
            cpu: '1'
            memory: 1G
      metadata:
        labels: *id001
