apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kibana
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kibana
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
