apiVersion: apps/v1
kind: Deployment
metdata:
  labels:
    name: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      name: prometheus
  template:
    metadata:
      labels:
        name: prometheus
    spec:
      containers:
      - image: prom/prometheus
        name: prometheus
        ports:
        - containerPort: 9090
          name: api
        resources:
          limits:
            cpu: '8'
            memory: 8G
          requests:
            cpu: '8'
            memory: 8G
