apiVersion: apps/v1
kind: Deployment
metdata:
  labels: &id001
    app.kubernetes.io/name: prometheus
  name: prometheus
spec:
  selector:
    matchLabels: *id001
  template:
    spec:
      containers:
      - image: prometheus
        name: prometheus
        resources:
          limits:
            cpu: '2'
            memory: 2G
          requests:
            cpu: '1'
            memory: 1G
      metadata:
        labels: *id001
