apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prometheus
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prometheus
  targetCPUUtilizationPercentage: 80
