apiVersion: apps/v1
kind: Deployment
metdata:
  name: grafana
  labels: &Labels
    app.kubernetes.io/name: grafana
spec:
  selector:
    matchLabels: *Labels
  template:
    spec:
      metadata:
        labels: *Labels
      containers:
        - name: grafana
          image: grafana
          ports:
            - containerPort: 5601
          resources:
            requests:
              cpu: "1"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
